# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-23 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', jsonfield.fields.JSONField(default=[[b'.', b' ', b'.', b' ', b'.', b' ', b'.'], [b' ', b'0', b' ', b'0', b' ', b'0', b' '], [b'.', b' ', b'.', b' ', b'.', b' ', b'.'], [b' ', b'0', b' ', b'0', b' ', b'0', b' '], [b'.', b' ', b'.', b' ', b'.', b' ', b'.'], [b' ', b'0', b' ', b'0', b' ', b'0', b' '], [b'.', b' ', b'.', b' ', b'.', b' ', b'.'], [b' ', b'0', b' ', b'0', b' ', b'0', b' '], [b'.', b' ', b'.', b' ', b'.', b' ', b'.'], [b' ', b'0', b' ', b'0', b' ', b'0', b' '], [b'.', b' ', b'.', b' ', b'.', b' ', b'.']])),
                ('winner', models.IntegerField(default=0)),
                ('turn', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_player1_games', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_player2_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
