# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-27 15:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20170824_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_pipe',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
