# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-28 10:04
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_auto_20170828_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=jsonfield.fields.JSONField(default=[[b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7', b'', b'\xc2\xb7']]),
        ),
    ]
