# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-28 15:44
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_auto_20170828_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=jsonfield.fields.JSONField(default=[[b'.', b'', b'.', b'', b'.', b'', b'.'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'.', b'', b'.', b'', b'.', b'', b'.'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'.', b'', b'.', b'', b'.', b'', b'.'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'.', b'', b'.', b'', b'.', b'', b'.'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'.', b'', b'.', b'', b'.', b'', b'.'], [b'', b'0', b'', b'0', b'', b'0', b''], [b'.', b'', b'.', b'', b'.', b'', b'.']]),
        ),
    ]
